import {
  type BackgroundColorProps,
  type BorderProps,
  backgroundColor,
  border,
  composeRestyleFunctions,
  createBox,
  type LayoutProps,
  layout,
  type SpacingProps,
  type SpacingShorthandProps,
  spacing,
  spacingShorthand,
  useRestyle,
} from '@shopify/restyle';
import {
  Pressable as RNPressable,
  type PressableProps as RNPressableProps,
  type StyleProp,
  type ViewStyle,
} from 'react-native';
import type { Theme } from '@/theme/theme';

export const Box = createBox<Theme>();
export type BoxProps = React.ComponentProps<typeof Box>;

type RestyleTypes = BackgroundColorProps<Theme> &
  SpacingProps<Theme> &
  LayoutProps<Theme> &
  BorderProps<Theme> &
  SpacingShorthandProps<Theme>;

export type PressableBoxProps = RNPressableProps & RestyleTypes;

// NOTE: Function to compose the style properties
const restyleFunctions = composeRestyleFunctions<Theme, RestyleTypes>([
  backgroundColor,
  spacing,
  spacingShorthand,
  layout,
  border,
]);

export const PressableBox = ({ style, ...rest }: PressableBoxProps) => {
  // NOTE: Extract the style properties from Restyle and the other props
  const { style: restyleStyle, ...props } = useRestyle(
    restyleFunctions,
    rest as PressableBoxProps,
  );

  return (
    <RNPressable
      style={(state) => {
        // NOTE: Resolve the user style if it's a function, or use it directly if it's an object
        const userStyle = typeof style === 'function' ? style(state) : style;
        // NOTE: Combine the style generated by Restyle with the user style
        return [restyleStyle, userStyle] as StyleProp<ViewStyle>;
      }}
      {...props}
    />
  );
};
